services:
  - type: web
    name: plataforma-monitoreo-satelital
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    rootDir: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

