services:
  - type: web
    name: plataforma-monitoreo-satelital
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    rootDir: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

